import os
import copy

BIN_DIR = os.environ['BIN_DIR'];
LIB_DIR = os.environ['LIB_DIR'];
env = DefaultEnvironment().Clone()

SOURCES = Glob("*.c")

env.Library(os.path.join(LIB_DIR, 'awtk_gl_wayland'), SOURCES)

env['LIBS'] = ['awtk_gl_wayland'] + env['LIBS']

